name: Nix Build

on: 
  pull_request:
  push:
    paths-ignore:
     - "README.md"
     - ".gitignore"
     - "Makefile"
     - ".gitattributes"
  workflow_run:
    workflows: [update-flake]
    types: [completed]
  workflow_dispatch:

jobs:
  build-nixos:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v4
      
      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: zackartz
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Build NixOS config ❄️"
        run: |
          nix build .\#nixosConfigurations."earth".config.system.build.toplevel 
